version: '3'

services:
  database:
    image: mariadb:latest 
    container_name: drupal_db
    restart: always
    secrets:
      - db_user
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: drupal_db
      MYSQL_USER_FILE: /run/secrets/db_user 
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql

  drupal:
    image: drupal:latest
    depends_on:
      - database
    container_name: drupal
    restart: always
    ports:
      - 8083:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites

secrets:
  db_user:
    file: .secrets/db_user.txt
  db_password:
    file: .secrets/db_password.txt

volumes:
  drupal_sites:
  db_data:

networks:
  default:
    external: true
    name: docker-network

